Repository stoplightio/ui-kit, pull requests merged in 2020-08, with the labels that each got.

#179 fix(code-viewer): reduce initial layout shift
  src/styles/components/Code/_base.scss
Labels: bug

#182 feat(code-viewer): align line numbers to the right
  src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
  src/styles/components/Code/_base.scss
Labels: bug

#180 feat(code-viewer): scroll overscan
  src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
  src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx
  src/CodeViewer/components/BlockCodeViewer/consts.ts
Labels: enhancement

#184 fix(code-editor): line numbers are off
  src/CodeEditor/index.tsx
  src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
  src/CodeViewer/components/InlineCodeViewer.tsx
  src/classes.ts
  src/styles/components/Code/_base.scss
Labels: bug, team/void-crew

#186 fix(code-viewer): line numbers are incorrect in certain cases
  src/CodeViewer/__tests__/Viewer.spec.tsx
  src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx
  src/CodeViewer/utils/__tests__/__snapshots__/astToReact.spec.ts.snap
  src/CodeViewer/utils/__tests__/__snapshots__/lineNumberify.spec.ts.snap
  src/CodeViewer/utils/__tests__/lineNumberify.spec.ts
  src/CodeViewer/utils/astToReact.ts
  src/CodeViewer/utils/lineNumberify.ts
  src/CodeViewer/utils/parseCode.ts
Labels: bug

#185 feat(table-of-contents): rowComponentExtraProps
  src/TableOfContents/index.tsx
  src/__stories__/TableOfContents/index.tsx
Labels: enhancement

#188 fix(code-viewer): get rid of trailing lines
  setupTests.ts
  src/CodeViewer/__tests__/Viewer.spec.tsx
  src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
  src/CodeViewer/components/BlockCodeViewer/ObservableSet.ts
  src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx
  src/CodeViewer/components/BlockCodeViewer/hooks/useSlicedBlocks.ts
  src/styles/components/Code/_base.scss
Labels: bug, team/void-crew

#191 build: enable esModuleInterop
  src/CodeViewer/__tests__/Viewer.spec.tsx
  src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
  src/CodeViewer/components/InlineCodeViewer.tsx
  src/SimpleTabs/Tab.tsx
  src/SimpleTabs/TabList.tsx
  src/SimpleTabs/TabPanel.tsx
  src/ThemeContainer/index.tsx
  tsconfig.json
Labels: team/void-crew
